### ISSUE TITLE
typo? readme contains example instead of examples in import URL

### ISSUE THREAD

**Issue by crookse** [udibo/test_suite#17]
Hey @KyleJune !

so i'm walking through your module and i noticed the following in the README section (https://github.com/udibo/test_suite#flat-test-grouping) errors out:

```typescript
import {
  getUser,
  resetUsers,
  User,
} from "https://deno.land/x/test_suite@0.10.1/example/user.ts";
```

found that it should be this?

```diff
- } from "https://deno.land/x/test_suite@0.10.1/example/user.ts 
+ } from "https://deno.land/x/test_suite@0.10.1/examples/user.ts
```

**Comment by KyleJune** [comment]
Good catch. I think it's because initially I just had a single example, then I changed to having multiple examples. I'll try fixing that this weekend before I go on vacation.
