### ISSUE TITLE
Add back each with shorthands to focus and ignore like describe and it

### ISSUE THREAD

**Issue by KyleJune** [udibo/test_suite#7]
The `describe` and `it` functions both have versions for easily focusing or ignoring them. The each function was added in test_suite v0.8.0 but does not have equivalent functions for easily focusing or ignoring them. Currently the only way to focus or ignore each cases is to use the test definition call signature so that you can pass an ignore or focus parameter.

**Comment by KyleJune** [comment]
The `each` function was temporarily removed in version 0.10.0. I plan to add back `each` but as a function property on `it` and `describe`. For this issue, `each` will have `only` and `ignore` function properties on it.

**Comment by fxrysh** [comment]
> I plan to add back `each` but as a function property on `it` and `describe`. For this issue, `each` will have `only` and `ignore` function properties on it.

So you mean something like this?
```js
it.each(...);
it.each.only(...);
it.each.ignore(...);

// Same thing for `describe.each`
```

**Comment by KyleJune** [comment]
Yes, that's exactly what I mean. Then for the definitions, they would extend the Describe/It Definitions to also have a cases. Not sure about it but I think it might be cool to have name be a string or function so that you can generate names on a per case basis from the parameters.

**Comment by KyleJune** [comment]
For the fn option, I think it should match the describe/it call signature but with all the case parameters added as args to the end of the fn's current argument list.

**Comment by KyleJune** [comment]
I think the cases option should be similar to jest cases on their each, but passed in the EachDefinition instead of using currying.
https://jestjs.io/docs/api#describeeachtablename-fn-timeout

**Comment by KyleJune** [comment]
I've decided against making this change. Anything accomplished with each could just as easily be accomplished with array forEach or a for loop. This is much more flexible than using each with cases and it makes the describe/it interface cleaner.

```ts
const data = [
  [1,2,3],
  [4,5,6],
];

data.forEach(case => it("name based on case", function() {
  // ...
}))

for (const case of data) {
  it("name based on case", function() {
    //...
  })
}

for (const [a, b, c] of data) {
  it("name based on case parameters a, b, and c", function() {
    //...
  })
}
```
